### ISSUE TITLE
Add Padding in the messages 

### ISSUE THREAD

**Issue by DhairyaBahl** [DhairyaBahl/React-Messenger-App#1]
All the messages looks very messy. There should be padding ( space between messages and border ) . 

- Add padding of 10-20 px in the messages.

**Comment by Jwright707** [comment]
Hi @DhairyaBahl , I would like to work on this. 👍

**Comment by DhairyaBahl** [comment]
> Hi @DhairyaBahl , I would like to work on this. 👍 

 @Jwright707 .  Go ahead and tell me if you need any help. 👍
