### ISSUE TITLE
Add a delete button

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#100]
Add a delete button to delete the message.
If you want to add this feature please assign me under gssoc21

**Comment by DhairyaBahl** [comment]
@garvitgupta13 where exactly are you going to add the delete button ? currently the app is not authenticated and then anybody will be able to delete messages of others. If you are trying to implement the functionality of deleting your own messages , then we can definitely try that ! kindly confirm.

**Comment by abhijeet007rocks8** [comment]
Till then you can add a down arrow button (at top right corner of  every message) and clicking on that opens dropdown menu with options: 
edit 
reply 
delete

**Comment by DhairyaBahl** [comment]
@garvitgupta13 What is the status of the issue ? Are you still working on this ? Kindly confirm it once. Otherwise I will close this issue.

**Comment by garvitgupta13** [comment]
Currently I am busy with my institute exams, If anyone wants to work on this issue then please go ahead

**Comment by SanskritiKushik5** [comment]
> Till then you can add a down arrow button (at top right corner of every message) and clicking on that opens dropdown menu with options:
> edit
> reply
> delete

Can I work on this as a GSSOC'21 Participant?

**Comment by DhairyaBahl** [comment]
@SanskritiKushik5 Yes !! Definitely ! I am assigning this to you ! All the best .

**Comment by SanskritiKushik5** [comment]
<img width="658" alt="messenger" src="https://user-images.githubusercontent.com/65829453/116357888-aa04f600-a81a-11eb-8802-c1906ff4abbd.PNG">
Is this okay?
Also, the sender's name isn't visible in dark mode... should I change that too? @DhairyaBahl

**Comment by abhijeet007rocks8** [comment]
@SanskritiKushik5 can you adjust the dropdown icon top the top right corner of the box.
And is the dropdown theme sensitive??

**Comment by SanskritiKushik5** [comment]
Is this fine now? @abhijeet007rocks8 
<img width="545" alt="messenger" src="https://user-images.githubusercontent.com/65829453/116894732-053a4c80-ac50-11eb-8f3a-7dde586e6f5f.PNG">
<img width="547" alt="messenger-dark" src="https://user-images.githubusercontent.com/65829453/116894747-08cdd380-ac50-11eb-9269-bd309812562e.PNG">

**Comment by abhijeet007rocks8** [comment]
can you shift the dropdown to little below as it is covering the button which doesnt look nice also there are white lines in dark mode. 
Just fix these two minor issues and make a pR

**Comment by SanskritiKushik5** [comment]
Okay.

**Comment by subhangi2731** [comment]
@abhijeet007rocks8 please assign this issue to me

**Comment by SanskritiKushik5** [comment]
@abhijeet007rocks8 You can assign it to @subhangi2731 because my laptop isn't working properly for few days!

> @abhijeet007rocks8 please assign this issue to me

**Comment by subhangi2731** [comment]
@abhijeet007rocks8 please assign this to me
