### ISSUE TITLE
Range-Error ! Invalid array length

### ISSUE THREAD

**Issue by DhairyaBahl** [DhairyaBahl/React-Messenger-App#103]
This error must be resolved ASAP which is visible in the current version of the app ! I am unable to deploy the same so kindly fix the same asap.

![Screenshot (1)](https://user-images.githubusercontent.com/71627983/111610315-39bd8a80-8801-11eb-89a7-ea22a769e5eb.png)

**Comment by DhairyaBahl** [comment]
@AdityaTeltia I've assigned this issue to you ! This is because this issue must be solved immediately so that I can deploy the website right away !

I am also assigning the other collaborators as well. Do specify who wants to work on the same ! Feel free to assign anyone if you guys want to just get this issue solved !

Thanks and regards :)

**Comment by AdityaTeltia** [comment]
Yes I am looking into this ! @DhairyaBahl

**Comment by DhairyaBahl** [comment]
@AdityaTeltia Thanks a lot !

**Comment by AdityaTeltia** [comment]
@DhairyaBahl  Seems to me like the recent commit you made with commit message `adding some changes` has crashed the app.

**Comment by DhairyaBahl** [comment]
@AdityaTeltia In that commit, I just added proper indentation ! Feel free to experiment with the commits in your local system ! after rectifying do add the screenshots and then push the commit ! I will review it and then we will merge it in the codebase.

**Comment by AdityaTeltia** [comment]
@DhairyaBahl So was it working back then after those changes !

**Comment by DhairyaBahl** [comment]
@AdityaTeltia It was showing other errors before that and I kept on rectifying them !

**Comment by AdityaTeltia** [comment]
Yeah I am trying ! It would help if you could assign it to @abhijeet007rocks8 @dilemmawalker also . So that the app can get back on track asap
Thankyou

**Comment by DhairyaBahl** [comment]
@AdityaTeltia No issues ! I am assigning them on this again !

**Comment by garvitgupta13** [comment]
I have fixed the issue
I found out that someone has deleted `FormControl`, `but` and `SendIcon` from the repo

**Comment by DhairyaBahl** [comment]
@garvitgupta13 Kindly create a PR for the same ! and do add the screenshots :)

Thank You

**Comment by garvitgupta13** [comment]
Hey, @DhairyaBahl  can I create a PR for this. This was urgent so I started fixing this issue without being assigned
