### ISSUE TITLE
Send message with the enter key

### ISSUE THREAD

**Issue by AmrutaKoshe** [DhairyaBahl/React-Messenger-App#105]
Currently in the app, your message is sent only when you click on the arrow button. We can keep a feature where the message is sent even after pressing the enter key in your keyboard (like other messaging apps) 
I would like to try this out under GSSOC'21 !

**Comment by DhairyaBahl** [comment]
@AmrutaKoshe I am assigning this issue to you ! All the best :)

**Comment by Jaagrav** [comment]
Can you please assign me as well for this issue or is the seat's already taken?

**Comment by DhairyaBahl** [comment]
@Jaagrav All the issues are assigned on the first come first serve basis and @AmrutaKoshe is already working on the issue. Kindly check out other issues.

All the best :)
