### ISSUE TITLE
Adding Smooth scrolling

### ISSUE THREAD

**Issue by Alenjojo** [DhairyaBahl/React-Messenger-App#106]
It would look much pretty when smooth scrolling is added.

**Comment by DhairyaBahl** [comment]
@Alenjojo Scrolling is already smooth ! What exactly are you suggesting ? Kindly explain the issue.

**Comment by Alenjojo** [comment]
Its not the usual ones that is been there as default. Its kinda static type. We can add functions so that it will work as in of iMessage.

**Comment by DhairyaBahl** [comment]
@Alenjojo Can you describe what you are saying through a video or gif ?

**Comment by abhijeet007rocks8** [comment]
@Alenjojo can you provide a reference to what you are implying like some sort of  website where it is implemented.

**Comment by DhairyaBahl** [comment]
@Alenjojo Will you be able to describe the issue in a proper manner ? Otherwise I will have to close this issue.

**Comment by DhairyaBahl** [comment]
@Alenjojo Will you be able to explain this issue to us ? Otherwise, I will close this issue. Kindly confirm it once.

**Comment by abhijeet007rocks8** [comment]
I am closing this issue.
