### ISSUE TITLE
there is another input field below the "Type a message"

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#111]
shall I remove that?  @DhairyaBahl 

![2021-03-21 (3)](https://user-images.githubusercontent.com/65683151/111905303-f1a49f00-8a70-11eb-939a-1e43f485e08d.png)

**Comment by DhairyaBahl** [comment]
@akshay1027 That shouldn't be there ! Ofcourse ! Remove that. Thanks for noticing the same :)
