### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by muthuannamalai12** [DhairyaBahl/React-Messenger-App#117]
I would like to add a code of conduct file as the code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum.

**Comment by DhairyaBahl** [comment]
@muthuannamalai12 That would be great ^_^ . You can work on the issue.

**Comment by muthuannamalai12** [comment]
@DhairyaBahl Could you please add the gssoc21 label and level label??

**Comment by DhairyaBahl** [comment]
#121 This has been merged ! So closing this issue.
