### ISSUE TITLE
Reduce distance between messages and input box in dark mode 

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#124]
Reduce the distance between messages and input box in dark mode to Improve UI. 

![2021-03-28_LI](https://user-images.githubusercontent.com/65683151/112754361-59229780-8ff9-11eb-9e4a-0bddfc84bdba.jpg)

**Comment by DhairyaBahl** [comment]
@akshay1027 Go Ahead ! Do add the Screenshots for your changes ^_^

**Comment by akshay1027** [comment]
yea sure @dilemmawalker , even i thought the same! will be happy to do it! Should I start a new issue or do it in this PR itself

**Comment by dilemmawalker** [comment]
I guess it could be done in same PR.

**Comment by akshay1027** [comment]
sure!

**Comment by dilemmawalker** [comment]
Yes it is actually looking a lot better now.
