### ISSUE TITLE
No send feature in mobile version and improvements in mobile version

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#125]
No, send feature in mobile or responsive version.

![2021-03-28 (5)_LI](https://user-images.githubusercontent.com/65683151/112754744-13ff6500-8ffb-11eb-9bca-08664e22b88b.jpg)

**Comment by DhairyaBahl** [comment]
@akshay1027 Yes , You can work on this issue ! and I think that mobile layout is also broken so do check that out too.
