### ISSUE TITLE
Enable socket connection between two users using Socket.IO 

### ISSUE THREAD

**Issue by joelerego** [DhairyaBahl/React-Messenger-App#126]
1. Currently, there is a TCP/IP connection between the client application and firebase.
2. It seems like all the chat messages come from a document in firebase. Every user can read this document in real-time as the document changes since firebase is a real-time database.
3. Initially, we could just use Socket.IO to broadcast messages. This would require two things -
    - Integrating `socket.io-client` in the frontend (Client)
    - Writing an express server from scratch that uses user id from the client.

**Comment by joelerego** [comment]
I would like to undertake this. Please do assign it to me.

**Comment by subhangi2731** [comment]
@abhijeet007rocks8 @DhairyaBahl Please assign this issue to me I want to work

**Comment by joelerego** [comment]
Hey, sure. Sorry got busy with work. You should assign it to @subhangi2731

**Comment by abhijeet007rocks8** [comment]
@subhangi2731 GO ahead

**Comment by subhangi2731** [comment]
thank you @abhijeet007rocks8 @joelerego I will work on this
