### ISSUE TITLE
Limiting messages

### ISSUE THREAD

**Issue by cherau** [DhairyaBahl/React-Messenger-App#133]
Currently there is no restriction in the number of messages displayed on the main page. Limiting the number of messages or letting the users explicitly click a button to load the messages would help avoid long scrolling and make the chat app look clean.

**Comment by DhairyaBahl** [comment]
Not sure about this issue ! @dilemmawalker @abhijeet007rocks8 What do you say about this ?

**Comment by abhijeet007rocks8** [comment]
Assuming someone has to access previous message then he would have to manually load the message chunks that isn't user-friendly.
1. We can add message tagging feature
2. a button in the bottom right to make the user reach the last message.

**Comment by dilemmawalker** [comment]
There is already another issue open to search for a particular message like the feature we have in whatsapp,
I guess that would be a better option & @cherau you can work on that issue as it still hasn't been resolved & would kinda like cover your point too.

**Comment by DhairyaBahl** [comment]
@dilemmawalker @abhijeet007rocks8 Thanks for looking in this matter. Feel free to close this issue if needed !

**Comment by abhijeet007rocks8** [comment]
@cherau any other suggestion or we can close this issue??

**Comment by cherau** [comment]
@abhijeet007rocks8 I am currently working on the issue #135 so I guess you can close this issue.
