### ISSUE TITLE
Message is not sending using enter key.

### ISSUE THREAD

**Issue by dilemmawalker** [DhairyaBahl/React-Messenger-App#135]
Messages are not being sent using enter key, if anyone is interested on working out this issue feel free to drop a message, I will assign you the same.

**Comment by cherau** [comment]
Interested

**Comment by dilemmawalker** [comment]
@cherau I have assigned you the issue, you can start working now.

**Comment by cherau** [comment]
Hey, I think the return key is working now.

**Comment by dilemmawalker** [comment]
Yeah you are right. I am closing the issue then.
