### ISSUE TITLE
Footer Enhancement

### ISSUE THREAD

**Issue by Sristi27** [DhairyaBahl/React-Messenger-App#137]
The footer can be fixed to the bottom of the screen.Now,it is a bit up from the bottom.

**Comment by abhijeet007rocks8** [comment]
Can you provide scshot of the issue for reference

**Comment by DhairyaBahl** [comment]
@Sristi27 Yes, you are right ! Footer is bit up from the screen and it looks weird. Same is the case with dark mode i.e. footer looks weird.

Do add the screenshots for the same so that we can refer to that image in the issue. Thanks ^_^

**Comment by Castella1313** [comment]
@DhairyaBahl @abhijeet007rocks8 

![Screenshot 2021-04-08 at 8 55 56 PM](https://user-images.githubusercontent.com/53293156/114053787-e1802280-98ac-11eb-9e63-186d68ca726a.png)
![Screenshot 2021-04-08 at 8 56 05 PM](https://user-images.githubusercontent.com/53293156/114053800-e5ac4000-98ac-11eb-8058-83a81e96a5bc.png)

**Comment by Sristi27** [comment]
> @Sristi27 Yes, you are right ! Footer is bit up from the screen and it looks weird. Same is the case with dark mode i.e. footer looks weird.
> 
> Do add the screenshots for the same so that we can refer to that image in the issue. Thanks ^_^

![Screenshot 2021-04-08 at 9 02 39 PM](https://user-images.githubusercontent.com/53037053/114054815-ce218700-98ad-11eb-9999-9dc40c6db170.png)

As we can see here,the input bar looks very weird due to the spacing.

**Comment by abhijeet007rocks8** [comment]
@Sristi27 Please go ahead and fix the issue.
Also try to reduce the input bar size and align it in middle it looks too long.

**Comment by Sristi27** [comment]
Okay will finish it by tomorrow and inform !

**Comment by Sristi27** [comment]
Previous:
![Screenshot 2021-04-11 at 1 38 51 PM](https://user-images.githubusercontent.com/53037053/114296906-516bf400-9acb-11eb-8e65-ee28a1e5370f.png)
![Screenshot 2021-04-11 at 1 38 39 PM](https://user-images.githubusercontent.com/53037053/114296912-57fa6b80-9acb-11eb-9a5f-bddb8b3a72de.png)




After modification:
![Screenshot 2021-04-11 at 1 36 21 PM](https://user-images.githubusercontent.com/53037053/114296814-ee7a5d00-9aca-11eb-8723-6401ecd6c00e.png)
![Screenshot 2021-04-11 at 1 36 13 PM](https://user-images.githubusercontent.com/53037053/114296815-f0442080-9aca-11eb-9c68-b097179446da.png)

This is how I have made it to look.I have modified the dark mode input box and also fixed it to bottom as you mentioned.
Also,according to your last comment I have tried to align it in the middle and reduce the input bar size

**Comment by Sristi27** [comment]
@DhairyaBahl Kindly review this.

**Comment by DhairyaBahl** [comment]
@Sristi27 Well Done !! But tell me about that color change on hovering over the message box. Is it still doing it ? I mean does the message gets highlighted when we hovers over it ? Confirm it once. 

If yes, create a PR for the same and I will merge it right away , otherwise make sure that hovering feature is still there and then create PR.

Great Job ^_^ All the best

**Comment by Sristi27** [comment]
Well, I haven't checked it as of now..Will check and confirm.
Thank you!

**Comment by Sristi27** [comment]
![Screenshot 2021-04-11 at 8 03 50 PM](https://user-images.githubusercontent.com/53037053/114308317-0cfb4b00-9b01-11eb-8d53-8ba3a494bfe3.png)


Is this the hover effect you are talking about?

**Comment by DhairyaBahl** [comment]
@Sristi27 Yes ! I am talking about that !

**Comment by Sristi27** [comment]
That works fine.I have created a pull request.Please review it @DhairyaBahl
