### ISSUE TITLE
in light mode inout bar is not visible

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#144]
in light mode inout bar is not visible, we can change the colour to light grey so that it will be visible! @DhairyaBahl @abhijeet007rocks8

**Comment by akshay1027** [comment]
i would like to work on this!

**Comment by abhijeet007rocks8** [comment]
Please share a schot explaining the issue??

**Comment by akshay1027** [comment]
Check this out @abhijeet007rocks8 

![16185098418013427994867719796309](https://user-images.githubusercontent.com/65683151/114917024-1e1ac380-9e43-11eb-891e-6da0cb320fb4.jpg)

**Comment by DhairyaBahl** [comment]
@akshay1027 I think we should add some sort of border around the input box ! what will you suggest @abhijeet007rocks8 ?

**Comment by akshay1027** [comment]
or changing colour slightly will do, let me know! @DhairyaBahl @abhijeet007rocks8

**Comment by abhijeet007rocks8** [comment]
add some dark color border and change the internal color to something light
