### ISSUE TITLE
Light/Dark theme button not working for about us page.

### ISSUE THREAD

**Issue by Shivangi-ch** [DhairyaBahl/React-Messenger-App#148]
![Screenshot from 2021-04-18 23-32-13](https://user-images.githubusercontent.com/57783826/115155633-82858f00-a09e-11eb-8205-9c6588ea8f42.png)

There should light theme for this page too.
I would like to work on this.

**Comment by DhairyaBahl** [comment]
Okay Go Ahead ! You  Can Work on the issue ! Thank You for noticing the issue ^_^

**Comment by Shivangi-ch** [comment]
Please Review!

**Comment by DhairyaBahl** [comment]
#150 Merged and successfully resolved this issue !
