### ISSUE TITLE
Empty name should not be allowed

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#151]
Currenlty if a person with name "    " can enter, but we must avoid it and throw a error for such username.
The message "hello" is send by user with name " ".
![image](https://user-images.githubusercontent.com/70805691/115409316-41f95300-a20f-11eb-8c3f-1c4aa9eb3d03.png)
Please assign this issue to me under `gssoc21`

**Comment by DhairyaBahl** [comment]
@garvitgupta13 Assigned !
