### ISSUE TITLE
Add feature to send emojis.

### ISSUE THREAD

**Issue by Shivangi-ch** [DhairyaBahl/React-Messenger-App#155]
I would like to add an emoji picker so that user will be able to send emojis .
Please assign this to me.

**Comment by Shivangi-ch** [comment]
@DhairyaBahl please assign this to me.

**Comment by abhijeet007rocks8** [comment]
@Shivangi-ch this feature is already available

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 you can send emojis from from phone using the google keyboard(which has its own emoji picker), but you can not send it from the desktop site(i.e. if you are using a laptop/desktop).
So, I think we should add an emoji picker!
![emoji](https://user-images.githubusercontent.com/57783826/115895920-8dfb0080-a478-11eb-9dc7-43fc61845d96.png)

**Comment by abhijeet007rocks8** [comment]
I think there is an issue already present for this refer to #83

**Comment by DhairyaBahl** [comment]
@Shivangi-ch Lets move the conversation to the issue #83 as mentioned above by abhijeet ! I am closing this issue ^_^
