### ISSUE TITLE
.eslintcache should be in .gitignore

### ISSUE THREAD

**Issue by vivek80801** [DhairyaBahl/React-Messenger-App#156]
[**.eslintcache**](https://github.com/DhairyaBahl/React-Messenger-App/blob/master/.eslintcache)  is exposing contributors file system. you can see it is exposing [this contributor](https://github.com/Shivangi-ch) file system. I can easily tell this contributor have **Linux OS** . This project is in home dirctory on his/her local device. This issue can easily be fixed by just adding one line to **.gitignore** file. 

```diff
+ .eslintcache
```

**Comment by DhairyaBahl** [comment]
would you like to work on this issue ?

**Comment by vivek80801** [comment]
@DhairyaBahl sure.

Thanks for assigning this issue to me.
