### ISSUE TITLE
Input box not responsive after re design

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#159]
Input box not responsive after re design, would like to make it responsive! @abhijeet007rocks8 @DhairyaBahl  

![2021-04-23](https://user-images.githubusercontent.com/65683151/115880005-e1b11e00-a467-11eb-9495-a255262ce39c.png)

**Comment by DhairyaBahl** [comment]
@akshay1027 Okayy ! Go Ahead ^_^
