### ISSUE TITLE
Message can't be send by pressing enter key.

### ISSUE THREAD

**Issue by Shivangi-ch** [DhairyaBahl/React-Messenger-App#162]
I think message should be send by pressing the enter key while using the desktop site.

**Comment by DhairyaBahl** [comment]
@Shivangi-ch Would you like to work on this issue ?

**Comment by Shivangi-ch** [comment]
Yes. Please assign this to me.@DhairyaBahl

**Comment by vivek80801** [comment]
@DhairyaBahl  please close this issue. This issue is already solved
