### ISSUE TITLE
The logo can be changed!

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#167]
The logo or the text colour can be changed to make them more attractive!

**Comment by akshay1027** [comment]
@DhairyaBahl @abhijeet007rocks8

**Comment by akshay1027** [comment]
The yellow colour can be changed to purple, it will be clean and will match the rest of UI!

**Comment by DhairyaBahl** [comment]
@akshay1027 feel free to make pr for the same ! If it looks better , then I will definitely merge it .
