### ISSUE TITLE
build directory is not included in .gitignore

### ISSUE THREAD

**Issue by CIPHERTron** [DhairyaBahl/React-Messenger-App#168]
Someone has pushed the build directory into the master branch 😶

**Comment by DhairyaBahl** [comment]
@CIPHERTron Would you like to work on this issue ? or should I assign it to someone else.

**Comment by CIPHERTron** [comment]
Naah.....I'm good
I just came across your repo and noticed that the build folder was pushed somehow.
Thus informed! Feel free to assign it to someone else :D

**Comment by DhairyaBahl** [comment]
@CIPHERTron Okay !! Thanks for creating the issue !

**Comment by vivek80801** [comment]
@DhairyaBahl I will love to work on this issue. if you want.

**Comment by N-Shar-ma** [comment]
Could I please be assigned to work on this issue?

**Comment by DhairyaBahl** [comment]
@N-Shar-ma Go Ahead !
