### ISSUE TITLE
On routing different paths, the tab is reloading.

### ISSUE THREAD

**Issue by hsnice16** [DhairyaBahl/React-Messenger-App#170]
**Problem**
When we are clicking on the about us or home button on the homepage. The page is getting reload. But as we are using react Js for the frontend. We can prevent it from reloading.

**Expected behavior**
When we click on the about us or home button, only the path should change. And this should happen without reloading the page.

**Comment by abhijeet007rocks8** [comment]
@hsnice16 are you a gssoc participant??

**Comment by hsnice16** [comment]
Yes, I am a gssoc participant.

**Comment by vivek80801** [comment]
@abhijeet007rocks8  Can you assign this issue to me?

I am not a gssoc participant. But I love to contribute to open source project

**Comment by hsnice16** [comment]
But, I want to work on it. Please assign it to me.

**Comment by abhijeet007rocks8** [comment]
@vivek80801 Thanks for the contribution.
