### ISSUE TITLE
Navbar UI enhancement.

### ISSUE THREAD

**Issue by Shivangi-ch** [DhairyaBahl/React-Messenger-App#182]
I think the navigation bar should be made more attractive and user-friendly.
I would like to work on this.
Please assign this to me.

**Comment by abhijeet007rocks8** [comment]
@Shivangi-ch  Please provide some exact idea that you would like to work upon

**Comment by Shivangi-ch** [comment]
I think the font size and logo size should be reduced.
Border of the buttons should not be there.
Theme toggle button should be  animated.
Hovering effect on the buttons should just be a simple underline of the basic color theme same as that of logo(gradient color).

**Comment by abhijeet007rocks8** [comment]
@Shivangi-ch Go Ahead

**Comment by Shivangi-ch** [comment]
@DhairyaBahl I am working on it.Will make a PR ASAP!
