### ISSUE TITLE
Major Bug: others' old messages with same username are wrongly shown as current user's messages

### ISSUE THREAD

**Issue by N-Shar-ma** [DhairyaBahl/React-Messenger-App#185]
## Description:
If another user has in the past used the same username as the current user, then that other user's messages are shown as the current user's messages (they are given a class of `user` instead of `guest`)

## Solution
I would like to correct this bug by changing the way user and guest class is given to a message. It won't be decided on the basis of username but instead by giving each user a unique id (using the uuid npm package)

**Comment by abhijeet007rocks8** [comment]
@N-Shar-ma are you gssoc participant??

**Comment by N-Shar-ma** [comment]
> @N-Shar-ma are you gssoc participant??

Yes I am

**Comment by abhijeet007rocks8** [comment]
Can you first share the scshot of the issue you mentioned ??
Also from next time do try to get yourself assigned first else it can cause pr confusion

**Comment by N-Shar-ma** [comment]
Here is a gif which shows that on choosing username as "Test" others' older messages sent from the same username, are shown as sent by the current user:
![](https://i.imgur.com/b9CbPi8.gif)
