### ISSUE TITLE
Reduce the size of footer on "about us" page

### ISSUE THREAD

**Issue by Shivangi-ch** [DhairyaBahl/React-Messenger-App#189]
The footer on about us page is a bit big(it covers the complete screen size) and  theme does not change in the footer, so i think it would look better if the footer was small in size.

**Comment by abhijeet007rocks8** [comment]
Can you add a scshot highlighting the issue???

**Comment by Shivangi-ch** [comment]
You can see in the screenshot the footer is too big.
![Screenshot from 2021-05-05 23-35-57](https://user-images.githubusercontent.com/57783826/117188504-c09ee480-adfa-11eb-82b5-af2ec4cbd914.png)
We have less content in the footer, So it can be fitted in a small space.

**Comment by abhijeet007rocks8** [comment]
@Shivangi-ch GO ahead

**Comment by DhairyaBahl** [comment]
@Shivangi-ch Make the PR for the same and I will merge it !! ATB ^_^
