### ISSUE TITLE
Messages are not loading[Bug]

### ISSUE THREAD

**Issue by Shivangi-ch** [DhairyaBahl/React-Messenger-App#192]
Their is a bug in the website - messages are not displayed.
I think this is due to the error that is shown in the console(see screenshot).
I think this has something to do with the the `Readmore` component in messages.js. I would like to try to fix it.
![Screenshot from 2021-05-07 22-00-34](https://user-images.githubusercontent.com/57783826/117481045-0df88e80-af80-11eb-99bb-4a24b8e7a977.png)

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8  please assign this!

**Comment by DhairyaBahl** [comment]
@Shivangi-ch Solve this issue ASAP ! This need to be resolved right away !! ATB !! Thank You !

**Comment by garvitgupta13** [comment]
Hey @DhairyaBahl I have fixed this bug
Can I create a PR to fix this issue.
![image](https://user-images.githubusercontent.com/70805691/117562651-253d9600-b0be-11eb-8396-79aca99931ab.png)
