### ISSUE TITLE
Responsive width of message Box

### ISSUE THREAD

**Issue by DhairyaBahl** [DhairyaBahl/React-Messenger-App#20]
### Description 

We are currently having fixed width of Message Box although height is varying . Fixed width was done so that It will look neater. But now we are having timestamps, so how about the responsive width also. I mean If a certain width is crossed then, increase its height. I am not totally sure about this idea. 

So suggestions open !!

I am adding picture of current status of the web-app.

![SS](https://user-images.githubusercontent.com/71627983/107353595-3a248080-6af3-11eb-9fec-b5f7ec3b3932.png)

**Comment by sagrawal9689** [comment]
Can I try this.

**Comment by DhairyaBahl** [comment]
@sagrawal9689 Of course !! Go Ahead :smile:
