### ISSUE TITLE
Theme of navbar does not switch properly on mobile view[bug]

### ISSUE THREAD

**Issue by Shivangi-ch** [DhairyaBahl/React-Messenger-App#211]
The theme change in navbar does not work for mobile view.
This issue can be seen in gif below.
![xsdfgbh](https://user-images.githubusercontent.com/57783826/117941125-6dabbc80-b327-11eb-8db1-37b489439620.gif)

**Comment by Shivangi-ch** [comment]
Please assign this issue to me.

**Comment by abhijeet007rocks8** [comment]
@Shivangi-ch Go Ahead
