### ISSUE TITLE
Bug: Nav icon (hamburger icon) is invisible in light mode

### ISSUE THREAD

**Issue by N-Shar-ma** [DhairyaBahl/React-Messenger-App#215]
## Screenshot:
![image](https://user-images.githubusercontent.com/68962290/117987418-505afc00-b2ef-11eb-97cd-27fed80a30e3.png)

Could you please assign this issue to me?

**Comment by Shivangi-ch** [comment]
@N-Shar-ma Already made an issue about problem with theme in navbar(#211), and currently working on it.

**Comment by N-Shar-ma** [comment]
> @N-Shar-ma Already made an issue about problem with theme of navbar in mobile view(#211), and currently working on it.

Oh alright then, I'll close this issue
