### ISSUE TITLE
Remove extra comments

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#217]
Some pages like [this](https://github.com/DhairyaBahl/React-Messenger-App/blob/master/src/components/contactForm/contactForm.js) consists of extra and unnecessary comments, which makes the code messy.

**Comment by abhijeet007rocks8** [comment]
Try adding meaning full comments too so that it helps other developers

**Comment by garvitgupta13** [comment]
Hey @abhijeet007rocks8 @DhairyaBahl it is a request that please merge PR:#224 before any other PR, because on every PR merge, it creates a merge conflict, since this PR involves changes in most of the javascript files
