### ISSUE TITLE
Clean the code.

### ISSUE THREAD

**Issue by Shivangi-ch** [DhairyaBahl/React-Messenger-App#220]
- Due to a lot of contributions, the code is messy right now. For example improper indentation, unesseccary spaces/tabs, lack of comments to explain the code and extra commented code.
- All this makes it difficult for beginner contributors to understand the code.

So the code should be cleaned.

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 Please assign!

**Comment by garvitgupta13** [comment]
This issue was already open in #217 
2 people working on the same issue is not correct

**Comment by Shivangi-ch** [comment]
@garvitgupta13 the issue you created is about extra comments, where as I have raised other isuues as well like ` improper indentation, unesseccary spaces/tabs, lack of comments to explain the code`. You can work on removing extra comments and i will work on the remaining ones.

**Comment by garvitgupta13** [comment]
> @garvitgupta13 the issue you created is about extra comments, where as I have raised other isuues as well like ` improper indentation, unesseccary spaces/tabs, lack of comments to explain the code`. You can work on removing extra comments and i will work on the remaining ones.

In that issue #217, @abhijeet007rocks8 requested me to add extra comments and using prettier I have fixed improper indentation also.
