### ISSUE TITLE
Add a features page.

### ISSUE THREAD

**Issue by Shivangi-ch** [DhairyaBahl/React-Messenger-App#221]
We can add a feature page which mentions the features of the app such as emojis, speech to text for sending messages(#218), dark/light theme, etc.
Below are some example screenshots for reference:-
![Screenshot from 2021-05-12 23-37-14](https://user-images.githubusercontent.com/57783826/118023411-24855800-b37b-11eb-93e9-11971c1c260e.png)
![Screenshot from 2021-05-12 23-37-23](https://user-images.githubusercontent.com/57783826/118023422-294a0c00-b37b-11eb-9caa-5ea3090393c8.png)

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8  Please assign!

**Comment by abhijeet007rocks8** [comment]
@Shivangi-ch Go Ahead
