### ISSUE TITLE
Add a "Speak Now" alert when mic is recording.

### ISSUE THREAD

**Issue by Shivangi-ch** [DhairyaBahl/React-Messenger-App#226]
Currently their is **no way to know if the mic has started listening**(except for a small red dot in the tab title). What we can do is show **a small pop up(near the mic) that says _"Speak Now"_ when the mic is cliked** and disappears when the users stop speaking.
Please assign me this issue under `gssoc21`

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 please assign!

**Comment by abhijeet007rocks8** [comment]
@Shivangi-ch  Go Ahead
