### ISSUE TITLE
Read More

### ISSUE THREAD

**Issue by DhairyaBahl** [DhairyaBahl/React-Messenger-App#25]
### Description

Currently this app shows full messages, it doesn't matter how long they are, chat will show full message. How about read more kind of a thing which will be great for the app. 

### Example Picture

![readmore](https://user-images.githubusercontent.com/71627983/108667775-e3aa3f80-74ff-11eb-92a3-0a0641b7bf73.jpg)

**Comment by shreyanshi16** [comment]
Hey @DhairyaBahl, I would like to work on this issue, could I?

**Comment by DhairyaBahl** [comment]
@shreyanshi16 Assigned ! Go Ahead and make a PR 😄 👍
