### ISSUE TITLE
footer does not changes on dark theme 

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#261]
In features page the footer does not change on darktheme
![image](https://user-images.githubusercontent.com/70805691/118407157-05e5d080-b69d-11eb-989d-a3ca83bbd371.png)

Please assign me this issue under `gssoc21`

**Comment by abhijeet007rocks8** [comment]
Refer Issue #209

**Comment by garvitgupta13** [comment]
> Refer Issue #209

In issue #242 the dark theme support for feature changes were merged, but still the footer does not change its color in features page.
I raised the issue specific to feature page.
