### ISSUE TITLE
Change the design of message box in dark theme

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#263]
The message box looks the same on both light and dark theme. 
We can change the look of message box under dark theme so it looks much better with the theme

Please assign me this issue under `gssoc21`

**Comment by abhijeet007rocks8** [comment]
Any specific suggestions or ideas??

**Comment by garvitgupta13** [comment]
> Any specific suggestions or ideas??

I will share it with you by tomorrow morning

**Comment by garvitgupta13** [comment]
Hey @abhijeet007rocks8 please let me know should I create a PR for this

**Comment by garvitgupta13** [comment]
please review this issue @DhairyaBahl  @abhijeet007rocks8
