### ISSUE TITLE
Enhance the design of input box

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#264]
We can enhance the design of input message field so that it looks better. 

Please assign me this issue under `gssoc21`

**Comment by abhijeet007rocks8** [comment]
Do you have any suggestions in mind?? like exactly what you wish to improve and how

**Comment by garvitgupta13** [comment]
![image](https://user-images.githubusercontent.com/70805691/118448776-08354280-b710-11eb-837b-e5f1d92183a8.png)

If you have a different idea than please let me know

**Comment by abhijeet007rocks8** [comment]
It looks good did you tried other combinations too because the  blackness in the starting can be reduced a little maybe using a lighter shade

**Comment by garvitgupta13** [comment]
> It looks good did you tried other combinations too because the blackness in the starting can be reduced a little maybe using a lighter shade

Sure, I will try with a lighter shade of black and will let you know

**Comment by garvitgupta13** [comment]
![image](https://user-images.githubusercontent.com/70805691/118537689-e5844780-b76a-11eb-8099-34fc4da93ac1.png)
I tried it with a lighter shade of black, if it correct should I create a PR

**Comment by abhijeet007rocks8** [comment]
Looks good

**Comment by garvitgupta13** [comment]
Hey @abhijeet007rocks8 Please add the gssoc21 level tags on that PR
