### ISSUE TITLE
Landing page theme doesn't changes

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#266]
Landing page is always black in both light and dark theme
![image](https://user-images.githubusercontent.com/70805691/118443000-fac88a00-b708-11eb-82b3-0a04bb5604e9.png)
![image](https://user-images.githubusercontent.com/70805691/118443052-103db400-b709-11eb-90c3-7b2fa9e43804.png)
Please aasign me this issue under `gssoc21`

**Comment by Shivangi-ch** [comment]
@garvitgupta13 Already an issue for this #256, Also made a pull request for this #268

**Comment by garvitgupta13** [comment]
> @garvitgupta13 Already an issue for this #256, Also made a pull request for this #268

Sorry me bad, I didn't noticed it
