### ISSUE TITLE
Bug: Welcome Dialogue Box does not submit when enter is pressed

### ISSUE THREAD

**Issue by N-Shar-ma** [DhairyaBahl/React-Messenger-App#271]
## Problem
On clicking the enter button, the name is submitted, but on pressing the enter key, nothing happens. This is bad UX and can frustrate a user

## Solution
On pressing the enter key from the keyboard, the form should be submitted (the name should be set, just like it is when clicking the Enter button)

Please assign this issue to me, I've already fixed this bug locally

**Comment by abhijeet007rocks8** [comment]
@N-Shar-ma  Go Ahead
