### ISSUE TITLE
Bug: Timestamp of latest message hidden under input bar in mobile view

### ISSUE THREAD

**Issue by N-Shar-ma** [DhairyaBahl/React-Messenger-App#275]
## Screenshot:
Currently it looks like this:
![image](https://user-images.githubusercontent.com/68962290/118563207-ff01a100-b722-11eb-96e4-8a3b4f0a1cb1.png)

I would like to add some more space after the last message so that there is no overlap, and everything is spaced properly. Like this:
![image](https://user-images.githubusercontent.com/68962290/118563704-e5ad2480-b723-11eb-8b38-e045dd7e6b33.png)

 Please assign this issue to me

**Comment by hardikshah197** [comment]
May I take up this issue? I can fix it soon @N-Shar-ma
