### ISSUE TITLE
Load only latest 50 messages instead of all

### ISSUE THREAD

**Issue by N-Shar-ma** [DhairyaBahl/React-Messenger-App#276]
## Problem
As this app is growing and is used more, the total number of messages is becoming very large and retrieving them all from firestore will get slow. Also, old messages are not usually relevant, so there's no reason for so much overhead

## Solution
Only fetching and showing the latest 50 messages will speed up load times and improve a user's experience, by showing only relevant content

**Comment by abhijeet007rocks8** [comment]
Nice idea but we can fetch the latest 50 messages 
But we must also need to find a way to access the previous messages (beyond 50) if user wants 
Do try to find a solution for this.

**Comment by N-Shar-ma** [comment]
> Nice idea but we can fetch the latest 50 messages
> But we must also need to find a way to access the previous messages (beyond 50) if user wants
> Do try to find a solution for this.

Sure, I'll make a PR for loading latest 50 messages soon, and after that make another PR to add a button at the top of all messages that on being clicked loads older messages
