### ISSUE TITLE
Add a button to load older messages at user's request

### ISSUE THREAD

**Issue by N-Shar-ma** [DhairyaBahl/React-Messenger-App#282]
This is in continuation of issue #276 

I want to add a button at the top of all the visible messages, which on clicking loads older messages in increments of 50. So, on loading the website 50 messages load, and on clicking this button once, latest 100 will load, on clicking again latest 150 will load, and so on. Hope this sounds good

I'll work on this once PR #280 is merged

**Comment by abhijeet007rocks8** [comment]
Sounds Good
