### ISSUE TITLE
Texts in about us are too small

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#283]
For some reason Texts in about us have become too small, maybe it has to do with the changes made by other developers! I would like to fix this!

**Comment by akshay1027** [comment]
![2021-05-19 (7)](https://user-images.githubusercontent.com/65683151/118824006-1b463f00-b8d7-11eb-9ef4-3cee1f6ac190.png)

**Comment by akshay1027** [comment]
@abhijeet007rocks8 @DhairyaBahl

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 @DhairyaBahl #283 and #284 can be merged into a single issue.
