### ISSUE TITLE
Bug in footer

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#288]
Bug in footer. the github icon is smaller when compared with other icons!!

![2021-05-19 (10)](https://user-images.githubusercontent.com/65683151/118827441-0028fe80-b8da-11eb-9ce6-e3c037f36549.png)

**Comment by akshay1027** [comment]
I would like to fix this bug, @abhijeet007rocks8

**Comment by garvitgupta13** [comment]
In issue #261 I raised the same issue before
So please assign this issue to me @abhijeet007rocks8
