### ISSUE TITLE
Adding illustrations in about us page

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#289]
Adding illustrations to the about us page would make it more modern! 

check out this website which I made, this would give a practical idea of what am saying:

https://pec-forum-landingpage.netlify.app/

**Comment by akshay1027** [comment]
@abhijeet007rocks8 I would like to work on this!

**Comment by abhijeet007rocks8** [comment]
@akshay1027 Looks Great Go ahead. Just remember to use purple instead of green as that theme is followed throughout the app
