### ISSUE TITLE
Fix Background image scrolling issue

### ISSUE THREAD

**Issue by Aniket1103** [DhairyaBahl/React-Messenger-App#29]
Currently, when we scroll the messages the background image too gets scrolled along with the messages. I was thinking this app should have a fixed background image. i.e. Background image shouldn't get scrolled along with the messages (like for example in WhatsApp), also later we can add a feature of providing an option to the user to change the background image.

**Comment by Aniket1103** [comment]
I will like to fix this issue as a part of GSsoc21, please assign it to me.

**Comment by DhairyaBahl** [comment]
@Aniket1103 Thanks for noticing it. Kindly fix that !  🔥 😄

**Comment by Aniket1103** [comment]
I fixed it, now should I create a pull request?
Kindly guide me a bit coz I am contributing for the first time

**Comment by DhairyaBahl** [comment]
@Aniket1103 You did everything perfectly. Thanks for contributing 😄
