### ISSUE TITLE
favicon and App Title

### ISSUE THREAD

**Issue by Himanshu16Singh** [DhairyaBahl/React-Messenger-App#32]
Can I make PR for favicon and app title ?

**Comment by DhairyaBahl** [comment]
@Himanshu16Singh 

Feel free to make a PR ! I will definitely review your changes ! Don't forget to add some screenshots of the changes you make ! 

Thanks 😄

**Comment by Himanshu16Singh** [comment]
Okay

**Comment by feni-katharotiya** [comment]
@Himanshu16Singh Hello, I am gssoc participant and would like to work on this issue.
