### ISSUE TITLE
Small font size in navbar

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#329]
In dark theme font size of the navbar is too small and barely visible
![image](https://user-images.githubusercontent.com/70805691/119237757-2362e080-bb5c-11eb-8350-b4e55e5b0891.png)

Please assign me this issue under `gssoc21`

**Comment by Shivangi-ch** [comment]
@garvitgupta13 Already an issue #284

**Comment by garvitgupta13** [comment]
> @garvitgupta13 Already an issue #284

The PR attached with issue is concerned over changing fontsize of navbar elements in light theme only
I have raised issue specific to dark theme
