### ISSUE TITLE
Navbar elements are not visible

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#331]
In dark theme navbar elements are not visible in mobile view
![image](https://user-images.githubusercontent.com/70805691/119237920-1397cc00-bb5d-11eb-9ee0-d36294485ac8.png)

Please assign me this issue under `gssoc21`

**Comment by Shivangi-ch** [comment]
Already an issue #284

**Comment by garvitgupta13** [comment]
> Already an issue #284

The PR attached with that issue is fixing navbar font size in light mode only
While I have raised issue specific to the mobile view of navbar.
