### ISSUE TITLE
Text in FAQ is barely readable

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#332]
In the faq section, the text is too small and inconvenient to read.
![image](https://user-images.githubusercontent.com/70805691/119238023-b5b7b400-bb5d-11eb-8b2a-633a2aace3ce.png)

Please assign me this issue under `gssoc21`

**Comment by Shivangi-ch** [comment]
Already an issue

**Comment by garvitgupta13** [comment]
> Already an issue

please let me know the issue number.
If it it already a opened issue, I will close this

**Comment by Shivangi-ch** [comment]
@garvitgupta13 #283
