### ISSUE TITLE
Navbar buttons are smaller in dark mode when compared with light mode

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#333]
see navbar links: smaller in dark mode when compared with light mode

![2021-05-23 (4)](https://user-images.githubusercontent.com/65683151/119241739-5914c300-bb76-11eb-8f22-46136eff0249.png)  

![2021-05-23 (3)](https://user-images.githubusercontent.com/65683151/119241737-574aff80-bb76-11eb-865e-5c5fa04f04cd.png)

**Comment by akshay1027** [comment]
I would like to fix this @abhijeet007rocks8 @DhairyaBahl

**Comment by garvitgupta13** [comment]
Already a issue #329 
I reuest @abhijeet007rocks8 to assign me this issue
