### ISSUE TITLE
Navbar buttons are smaller in mobile screen

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#334]
![2021-05-23 (5)](https://user-images.githubusercontent.com/65683151/119242005-1bb13500-bb78-11eb-82e0-d6c34665e01b.png)

**Comment by akshay1027** [comment]
@abhijeet007rocks8 @DhairyaBahl i would like to work on this!

**Comment by garvitgupta13** [comment]
I already opened the issue #329 
So I request @abhijeet007rocks8 to assign me this issue
