### ISSUE TITLE
Input box not responsive in dark mode

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#336]
![2021-05-23](https://user-images.githubusercontent.com/65683151/119242062-92e6c900-bb78-11eb-9ebf-771d4c732c9f.png)

**Comment by akshay1027** [comment]
@abhijeet007rocks8 @DhairyaBahl i would like to work on this

**Comment by tanishq-arya** [comment]
@abhijeet007rocks8 can I work on this ?
