### ISSUE TITLE
signin page not responsive

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#339]
![2021-05-23 (10)](https://user-images.githubusercontent.com/65683151/119242893-63878a80-bb7f-11eb-8d32-2d308f0547fb.png)

**Comment by akshay1027** [comment]
i would like to fix this @abhijeet007rocks8 @DhairyaBahl

**Comment by tanishq-arya** [comment]
@abhijeet007rocks8 can I work on this ?
