### ISSUE TITLE
Why no limitations to number of assigned issues per person 

### ISSUE THREAD

**Issue by anjali1102** [DhairyaBahl/React-Messenger-App#345]
generally, it's 3 assigned task per person @abhijeet007rocks8  @DhairyaBahl

**Comment by abhijeet007rocks8** [comment]
@anjali1102 Can you specify the issue more precisely or provide some reference??

**Comment by anjali1102** [comment]
There are contributors who having assigned issues ( more than 3 ) in this repository. Is this not allowed in other projects of GSSOC

**Comment by abhijeet007rocks8** [comment]
I didn't heard of such a rule 
People want to contribute issue are assigned to them and they are pushing PR regularly so they are being assigned
