### ISSUE TITLE
Can we setup the boilerplate for the react native app, since it has been mentioned in the GSSoC description? 

### ISSUE THREAD

**Issue by lopeselio** [DhairyaBahl/React-Messenger-App#39]
I wanted to setup the mobile app for the same app

**Comment by DhairyaBahl** [comment]
@lopeselio Someone is already working on this issue and creating the native app for the same. Do check out some other issues or create your own like this. 

Happy Learning 😄

**Comment by lopeselio** [comment]
Can I have the link to the same repo? So that I can contribute to it as well.

**Comment by DhairyaBahl** [comment]
That repo is not the part of the GSSOC 2021. So sorry ! But if you want then I can talk to the gssoc organisers about that !

**Comment by lopeselio** [comment]
Tbh, this was the only react/react native project for gssoc I guess. That's why I asked.
