### ISSUE TITLE
 custom dark and light theme for the individual faq

### ISSUE THREAD

**Issue by akshay1027** [DhairyaBahl/React-Messenger-App#393]
reference #392

**Comment by akshay1027** [comment]
@abhijeet007rocks8 I would like to fix this!

**Comment by abhijeet007rocks8** [comment]
Exactly what fix are aiming at ?? can you explain

**Comment by akshay1027** [comment]
i will show with manually changing it show that you can easily understand

**Comment by akshay1027** [comment]
custom background for faq on toogle of dark mode light mode button:

![2021-05-26 (1)](https://user-images.githubusercontent.com/65683151/119640992-d1111080-be36-11eb-8334-7655f8b58505.png)

without custom background:

![2021-05-26](https://user-images.githubusercontent.com/65683151/119641137-f7cf4700-be36-11eb-9867-7b37ae3a02c4.png)

**Comment by akshay1027** [comment]
like this for lightmode as well
 @abhijeet007rocks8 please let me know
