### ISSUE TITLE
[Content] : About us,Features

### ISSUE THREAD

**Issue by tanishq-arya** [DhairyaBahl/React-Messenger-App#405]
Improve the content on about us page & features page. Content is as important as the product itself.

![image](https://user-images.githubusercontent.com/77333275/119544398-4802c680-bdaf-11eb-86f9-5e9dda7f33be.png)
<hr>
Improve catch phrases on the features page. 

![image](https://user-images.githubusercontent.com/77333275/119544115-0c67fc80-bdaf-11eb-8da6-279ffb5086e9.png)

**Comment by tanishq-arya** [comment]
@abhijeet007rocks8 please assign me this issue.

**Comment by abhijeet007rocks8** [comment]
@tanishq-arya Edit the content in website after getting approval of the content

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/120066806-d15b1700-c095-11eb-9410-ef0fbb9eb003.png)

FEATURES
![image](https://user-images.githubusercontent.com/77333275/120066815-dc15ac00-c095-11eb-8b06-2cdfb5ead15d.png)
![image](https://user-images.githubusercontent.com/77333275/120066819-e20b8d00-c095-11eb-9693-ada41cbfa59d.png)
![image](https://user-images.githubusercontent.com/77333275/120066822-e768d780-c095-11eb-9f51-98973ece04b9.png)
![image](https://user-images.githubusercontent.com/77333275/120066825-ed5eb880-c095-11eb-9da4-6570eba7f93e.png)

ABOUT
![image](https://user-images.githubusercontent.com/77333275/120066836-f780b700-c095-11eb-846d-68246c9ab815.png)
![image](https://user-images.githubusercontent.com/77333275/120066837-fcde0180-c095-11eb-8687-9157ed15000e.png)

@abhijeet007rocks8 How is this ? I have made the changes locally. If you want anything changed let me know or else should I make a PR if this looks good to you.

**Comment by abhijeet007rocks8** [comment]
Looks good make the PR
