### ISSUE TITLE
New Feature : Add Email-autocomplete functionality.

### ISSUE THREAD

**Issue by Shivangi-ch** [DhairyaBahl/React-Messenger-App#409]
I would like to add email autocomplete in  signup form.

**Comment by abhijeet007rocks8** [comment]
Email Auto complete like how will it work 
How will it work because email service provider like Gmail, outlook will be there ??

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 I woluld be using an autocomplete React component for email fields inspired by Auto-Email JQuery plugin.
Once the user start typing his email , it will autocomplete.
Demo:
![Screenshot from 2021-05-26 17-40-26](https://user-images.githubusercontent.com/57783826/119657483-94024980-be49-11eb-9c6d-f7fe5f24bf70.png)
