### ISSUE TITLE
Redesign UI and Improvements

### ISSUE THREAD

**Issue by Sanchit-Soni** [DhairyaBahl/React-Messenger-App#44]
1.The colour combination of the page can be improved a lot.
2.The Name and logo can also be changed and also the styles of the message can also be improved a lot.
3.Choosing the matching font.
4.Firebase Authentication can also be added.

**Comment by Sanchit-Soni** [comment]
I can work on this issue.

**Comment by DhairyaBahl** [comment]
@Sanchit-Soni all of these issues are already being solved by someone and issue means a single issue not a group of issues. So try to find an unassigned issue or create new one on which nobody is working on right now !

Thanks :)

**Comment by Sanchit-Soni** [comment]
okay!
