### ISSUE TITLE
Placement of theme button in the navbar

### ISSUE THREAD

**Issue by dig9074vijay** [DhairyaBahl/React-Messenger-App#46]
Hey @DhairyaBahl !
I just noticed that the button to change the theme is not aligned properly in the navbar.
I would like to align it with the messenger logo. [GSSOC`21 participant]
<img width="1439" alt="Screenshot 2021-03-10 at 11 10 13 PM" src="https://user-images.githubusercontent.com/55308273/110672569-c6f75280-81f5-11eb-94c2-b758fde54b71.png">

**Comment by DhairyaBahl** [comment]
@dig9074vijay I am sorry but someone is already working on this same issue.

**Comment by dig9074vijay** [comment]
> @dig9074vijay I am sorry but someone is already working on this same issue.

Oh got it!
