### ISSUE TITLE
Enhancement of the footer component

### ISSUE THREAD

**Issue by ankita-04** [DhairyaBahl/React-Messenger-App#49]
![image](https://user-images.githubusercontent.com/45062304/110674760-39693200-81f8-11eb-9ce8-274dd8701f0d.png)

 Here, I want to modify the text input field and send button at the footer. Please assign me these issues. I am a GSSOC'21 participant.

**Comment by DhairyaBahl** [comment]
@ankita-04 Sorry but UI of the app is completely changed. Kindly recheck the website and suggestions are still open. For the time being i am closing this issue. Feel free to open another if you want to suggest something.

Happy Learning 😄
