### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#491]
I pulled the latest changes and observed that in mobile view the FAQ is not visible.
I have already fixed this issue in PR #448, but due to PR #473 these changes were removed.
I would like to fix it again
![image](https://user-images.githubusercontent.com/70805691/120069249-8267ae80-c0a2-11eb-9d1d-a3b53f033bfd.png)

Please assign me this issue under `gssoc21`

**Comment by Saatvik21** [comment]
I've fixed this in #518

**Comment by garvitgupta13** [comment]
I have raised this issue specific to mobile view.
If you have fixed this for mobile view also then please send me a screenshot of that.

**Comment by Saatvik21** [comment]
> > I've fixed this in #518
> 
> I have raised this issue specific to mobile view.
> If you have fixed this for mobile view also then please send me a screenshot of that.

![Screenshot_7](https://user-images.githubusercontent.com/61618767/120077842-ff5a4e80-c0c9-11eb-9862-dbeb4fd9fc6f.png)

**Comment by garvitgupta13** [comment]
LGTM
