### ISSUE TITLE
Better UI colors

### ISSUE THREAD

**Issue by DhairyaBahl** [DhairyaBahl/React-Messenger-App#5]
Current colors of the app not look very professional. Suggestion Open for better UI colors.

**Comment by Shwetang550** [comment]
As a GSSoC'21 participant I'ld love to contribute to this part of the project 😄

**Comment by DhairyaBahl** [comment]
@Shwetang550 I would highly recommend that you should work on one issue at a time but you can always give suggestions for better UI colors. I will see them and If they look good then you can create a PR for that !

**Comment by Shwetang550** [comment]
Okay :)

**Comment by SanskritiKushik5** [comment]
Can I suggest a better UI (colors)?!
As a GSSOC'21 participant, I would really love to do that!

**Comment by DhairyaBahl** [comment]
@SanskritiKushik5 this is a discuss labelled issue so you can definitely give your suggestions. If they look good for the app then I will definitely merge them in the codebase. 😄 👍

**Comment by SanskritiKushik5** [comment]
1. We can use glass morphism for chats which will really look classic.
2. We can round up the border of the text input box, and lighten the color of the placeholder.
3. In the light mode, the input box isn't properly visible(or eye-catching), so we can change the color contrast for better visibility.
4. The color of the Header and Footer can be a bit darkened in light mode.. which can make the app look more beautiful!

This is the first time I am writing about an issue.. so please correct my way.. if I am wrong somewhere!

**Comment by DhairyaBahl** [comment]
@SanskritiKushik5 You wrote in the perfect way 😄. I think you can work on this issue and I am assigning this to you. Feel free to ask if you have any more doubts. All of your ideas seems great to me. Go Ahead and make a PR and don't forget to add the screenshots of the changes that you make. 

All the best 👍

**Comment by SanskritiKushik5** [comment]
Thank you Sir!

**Comment by DhairyaBahl** [comment]
@SanskritiKushik5 Thanks for solving this issue.

**Comment by SanskritiKushik5** [comment]
Welcome!
