### ISSUE TITLE
Messenger logo is distorted in Safari

### ISSUE THREAD

**Issue by dig9074vijay** [DhairyaBahl/React-Messenger-App#51]
### **In Safari:**
<img width="1440" alt="Screenshot 2021-03-11 at 12 27 33 PM" src="https://user-images.githubusercontent.com/55308273/110748063-3e17ff80-8265-11eb-96f3-9be9d3477971.png">

### **In Chrome:**

<img width="1440" alt="Screenshot 2021-03-11 at 12 29 58 PM" src="https://user-images.githubusercontent.com/55308273/110748290-86cfb880-8265-11eb-97b6-640d36d43b3d.png">

@DhairyaBahl I would like to fix it as a gssoc`21 participant. 😁

**Comment by DhairyaBahl** [comment]
@dig9074vijay Go Ahead !

**Comment by dig9074vijay** [comment]
Hey @DhairyaBahl! My contribution wasn't counted in GSSOC, I think you need to add the labels in the PR I created.

**Comment by DhairyaBahl** [comment]
@dig9074vijay Okay no issues, I will check that out and will add appropriate labels.
