### ISSUE TITLE
fixing the size of the message sent duration

### ISSUE THREAD

**Issue by Himika-Mishra** [DhairyaBahl/React-Messenger-App#61]
Hi @DhairyaBahl , 
I think the font size of the updated time while sending the message is too big as its distracting while reading the messages .
I think u got my point. If you will assign me I will start working on it and will communicate too if I get Stuck somewhere.
Thanks

**Comment by DhairyaBahl** [comment]
@Himika-Mishra Yes! you can work on this issue :)

**Comment by Himika-Mishra** [comment]
Thanx a lot!! And will fix the font style too to look more realistic .
Working on it!!

**Comment by DhairyaBahl** [comment]
@Himika-Mishra All the best 🔥

**Comment by Himika-Mishra** [comment]
Hi , I forked this app in my repository through codesandbox..... 2 hrs
earlier I was able to see the messages and now i m not .
can u plz help me out.

thanks

**Comment by Himika-Mishra** [comment]
Hi, the app link is not working too please check it out once.

**Comment by DhairyaBahl** [comment]
Thanks for solving this issue @Himika-Mishra . Do checkout other issues as well.

**Comment by Himika-Mishra** [comment]
Thank you so much. yes I will checkout other issues too.
