### ISSUE TITLE
Building a sign in and sign up Page/Window

### ISSUE THREAD

**Issue by Ritu7683** [DhairyaBahl/React-Messenger-App#62]
I would like to work on this issue. Kindly assign this to me @DhairyaBahl

**Comment by DhairyaBahl** [comment]
Are you talking about authentication in this issue ? @Ritu7683

**Comment by Ritu7683** [comment]
Yes ....Okay that's totally fine @DhairyaBahl

**Comment by Ritu7683** [comment]
@DhairyaBahl  Shall i delete this issue then ?

**Comment by DhairyaBahl** [comment]
@Ritu7683 Yes you should ! sorry for inconvenience caused. Do checkout some other issues.

**Comment by Ritu7683** [comment]
@DhairyaBahl  I don't have the permission to delete this. Can you **delete** it?

**Comment by DhairyaBahl** [comment]
@Ritu7683 No issues !
