### ISSUE TITLE
[BUG]: Fixing compilation error

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#639]
![image](https://user-images.githubusercontent.com/70805691/120136813-9de0cf80-c1f0-11eb-8cbc-a949e582fa39.png)

Please assign me this issue under `gssoc21`

**Comment by tanishq-arya** [comment]
Already solved #570

**Comment by garvitgupta13** [comment]
> Already solved #570

![image](https://user-images.githubusercontent.com/70805691/120139048-4b55e200-c1f5-11eb-8634-6056635ecf45.png)
Your PR doesn't fix anything, however, on pulling the latest commit I observed the compilation error hence fixed it

**Comment by tanishq-arya** [comment]
I don't know  why it's 0 but the files are modified when I view the commits.
![image](https://user-images.githubusercontent.com/77333275/120139467-2746d080-c1f6-11eb-957b-96a1121862d0.png)

**Comment by garvitgupta13** [comment]
> I don't know why it's 0 but the files are modified when I view the commits.
> ![image](https://user-images.githubusercontent.com/77333275/120139467-2746d080-c1f6-11eb-957b-96a1121862d0.png)

There is 0 changes because the files you changes were already fixed in pervious PR, but still there was a extra div in signup.jsx which I fixed

**Comment by garvitgupta13** [comment]
![image](https://user-images.githubusercontent.com/70805691/120147705-b1963100-c204-11eb-9dfa-88650392cad0.png)
The error still exists because the form and extra div tag is closed twice and the div with class loginbutton is not closed.

I have fixed this issue in PR
@abhijeet007rocks8 please review the PR
