### ISSUE TITLE
Add a dialog box for name input

### ISSUE THREAD

**Issue by AnjaliPatle** [DhairyaBahl/React-Messenger-App#64]
Hey! Currently we use a simple browser prompt to ask the user for their name. I would like to add a dialog box in place of the default prompt. I'll be using Material UI for this. Please let me know if I can work on this issue. I'm a GSSOC'21 participant.

**Comment by DhairyaBahl** [comment]
@AnjaliPatle Ofcourse ! Go Ahead ! That would be pretty awesome

**Comment by AnjaliPatle** [comment]
@DhairyaBahl I have implemented this. I'm attaching a screenshot below. Please let me know your opinions and if it seems fine to you then I'll create a PR!

![image](https://user-images.githubusercontent.com/50516607/111161217-e6f59000-85c0-11eb-9790-7068f782b0e2.png)

**Comment by DhairyaBahl** [comment]
@AnjaliPatle This seems to be perfect. Great Job 🔥 Looking forward to PR for the same.

**Comment by AnjaliPatle** [comment]
@DhairyaBahl  Thanks!
