### ISSUE TITLE
Removing Text Overflow

### ISSUE THREAD

**Issue by AnjaliPatle** [DhairyaBahl/React-Messenger-App#65]
Hey! I noticed that the text inside the message box overflows in case of long messages. I'd like to work on this issue and remove the overflow. I'm a GSSOC'21 participant.

![image](https://user-images.githubusercontent.com/50516607/110932214-2fa71200-8351-11eb-90ef-1b442799faca.png)

**Comment by DhairyaBahl** [comment]
@AnjaliPatle Yes you can start working on the issue.

**Comment by DhairyaBahl** [comment]
@AnjaliPatle What is the status ? Kindly keep me updated !

**Comment by AnjaliPatle** [comment]
I've created a PR for this issue. Kindly checkout PR #75 .

**Comment by abhijeet007rocks8** [comment]
Merged with PR #75
