### ISSUE TITLE
Broken mobile Layout

### ISSUE THREAD

**Issue by DhairyaBahl** [DhairyaBahl/React-Messenger-App#66]
Android layout of this app must be fixed as soon as possible.

![WhatsApp Image 2021-03-12 at 5 51 19 PM](https://user-images.githubusercontent.com/71627983/110939617-b234cf00-835b-11eb-873e-7ac39146cbfd.jpeg)

**Comment by DhrutikPatel** [comment]
@DhairyaBahl can I work on it?

**Comment by DhairyaBahl** [comment]
@DhrutikPatel Yes ! Go ahead

**Comment by sardonicankita** [comment]
Is this issue still open. Can I work on this?

**Comment by DhairyaBahl** [comment]
@sardonicankita Sorry ! But this issue is resolved now !
