### ISSUE TITLE
Button size on mobile

### ISSUE THREAD

**Issue by tanishq-arya** [DhairyaBahl/React-Messenger-App#671]
Fix button size on mobile view.
![image](https://user-images.githubusercontent.com/77333275/120171483-b74d4000-c21f-11eb-8c4d-c89044ebfb8f.png)

**Comment by tanishq-arya** [comment]
@abhijeet007rocks8 please assign this to me.

**Comment by YASH-YADAV-dynamo** [comment]
hey i would love to work on this issue under GSSOC'24 ,please assign me this

**Comment by abhijeet-chatterjee** [comment]
> @abhijeet007rocks8 please assign this to me.
@tanishq-arya I am not the maintainer for this project anymore.
