### ISSUE TITLE
Adding some text-boxes enhancements 

### ISSUE THREAD

**Issue by Himika-Mishra** [DhairyaBahl/React-Messenger-App#68]
Hi, 
@DhairyaBahl I want to make some changes to the textboxes while hovering onto them to make them look trendy.
It will become somewhat different from all the other messaging apps.
I think u got my point .
Kindly assign me this issue so that I can work on it ASAP.
thanks,
Himika Mishra

**Comment by DhairyaBahl** [comment]
@Himika-Mishra I am assigning this issue to you but first try to merge the PR for your first issue. That way you will also not get confused between multiple issues. Hope you got my point.

All the best 🔥

**Comment by Himika-Mishra** [comment]
Okay thanx. I have done that and it got merged too. 
Now will be working on this issue.

**Comment by DhairyaBahl** [comment]
Resolved
