### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohank2502** [DhairyaBahl/React-Messenger-App#69]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by DhairyaBahl** [comment]
@rohank2502 Ofcourse ! Go Ahead .

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 Ofcourse ! Go Ahead .

Thanks !!
