### ISSUE TITLE
Native App Issue : Firebase Integration  

### ISSUE THREAD

**Issue by abhijeet007rocks8** [DhairyaBahl/React-Messenger-App#77]
Create Firebase connection and login/signup feature.

1- Create a functional authentication feature.
2- Login screen will have 2 input fields namely email and password as
3- Sign up screen will have 3 fields email, password and image (for now)

(do not focus on css too much try to make functional)
Design the layout and update so that we can test with firebase connection.

**Comment by divanshurox** [comment]
I would like to work on this.

**Comment by abhijeet007rocks8** [comment]
Go ahead @divanshurox

**Comment by kunal-j10** [comment]
@abhijeet007rocks8 I would like to work as a gssoc'21 participant

**Comment by abhijeet007rocks8** [comment]
This is assigned to @divanshurox 
@kunal-j10  can work on the other issue for message

**Comment by divanshurox** [comment]
@abhijeet007rocks8  please check the video that I have attached below, auth with image uploads works from my side.Should i put a PR?

https://drive.google.com/file/d/1inj8HmvKEPkgIoDHih_n4f7EgOv1qW4b/view?usp=sharing

**Comment by abhijeet007rocks8** [comment]
@divanshurox Great Work 
Can you show the respective uploaded profile image on welcome screen along with email on the welcome screen??

**Comment by divanshurox** [comment]
Sure. I will.

**Comment by divanshurox** [comment]
@abhijeet007rocks8 I think we can close this issue if its completed?

**Comment by abhijeet007rocks8** [comment]
Closed with PR #80 by @divanshurox
