### ISSUE TITLE
Change the Text box sizes 

### ISSUE THREAD

**Issue by Himika-Mishra** [DhairyaBahl/React-Messenger-App#81]
Since in the current one the size of the textboxes are very big. so it is becoming for user to chat .
Please assign me to change it so that I start working on it. @DhairyaBahl 

Thanks 
Himika Mishra

**Comment by DhairyaBahl** [comment]
@Himika-Mishra Would love to have you working on the issue. All the best

**Comment by Himika-Mishra** [comment]
Thanx a lot @DhairyaBahl .

**Comment by bishakhne0gi** [comment]
Can I work on this? @abhijeet007rocks8

**Comment by Himika-Mishra** [comment]
I had already been assigned and PR has already been merged .

**Comment by DhairyaBahl** [comment]
@Himika-Mishra Are you still working on some issues of this project ?

**Comment by Himika-Mishra** [comment]
Nopes. ilIt got solved previously only
