### ISSUE TITLE
enchance the text box colors 

### ISSUE THREAD

**Issue by Himika-Mishra** [DhairyaBahl/React-Messenger-App#82]
I want to change the text box colors to somewhat glossy as to make it trendy and new.

Please assign this task to me so that I start working on it. @DhairyaBahl Please assign it to me.

Thanks
Himika Mishra

**Comment by DhairyaBahl** [comment]
@Himika-Mishra Assigned ! All the best 🔥

**Comment by Himika-Mishra** [comment]
Thanx a lott!!
