### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [DhairyaBahl/React-Messenger-App#84]
Hey! I would like to add the following in contributing.md
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
It will mention all with steps so that even a beginner in open-source can contribute easily
I would like to work on it as a part of GSSOC'21

**Comment by DhairyaBahl** [comment]
@khareyash05 Ok ! Go Ahead

**Comment by khareyash05** [comment]
@DhairyaBahl Created a PR Have  a look!
