### ISSUE TITLE
Read More Improvements

### ISSUE THREAD

**Issue by DhairyaBahl** [DhairyaBahl/React-Messenger-App#96]
Currently the readmore feature is fully functional but there are some problems with that. 

1. we can't differentiate it from the rest of the text due to same color.
2. on hovering cursor over that it doesn't changes color
3. on hovering cursor over it, cursor type doesn't change.

**Comment by AnjaliPatle** [comment]
I would like to work on this issue @DhairyaBahl 
Kindly assign it to me!

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by garvitgupta13** [comment]
Please assign this issue to me under gssoc21

**Comment by DhairyaBahl** [comment]
@garvitgupta13 and @AshuKV , every issue is assigned on first come first serve basis.
