### ISSUE TITLE
Disable empty messages 

### ISSUE THREAD

**Issue by garvitgupta13** [DhairyaBahl/React-Messenger-App#99]
Currently, we can send empty messages in this app.  We need to disable it
![image](https://user-images.githubusercontent.com/70805691/111381773-265cd300-86cc-11eb-8331-44979eca2119.png)

**Comment by garvitgupta13** [comment]
Please assign this issue to me under gssoc21

**Comment by DhairyaBahl** [comment]
@garvitgupta13 Assigned ! All the best 🔥
